export const SAVE_USER_EMAIL = 'SAVE_USER_EMAIL';
export const REQUEST_CURRENCIES_INITIALS = 'REQUEST_CURRENCIES_INITIALS';
export const RECEIVE_CURRENCIES_INITIALS = 'RECEIVE_CURRENCIES_INITIALS';
export const SAVE_EXPENSE = 'SAVE_EXPENSE';
export const REQUEST_EXCHANGE_RATES = 'REQUEST_EXCHANGE_RATES';
export const RECEIVE_EXCHANGE_RATES = 'RECEIVE_EXCHANGE_RATES';
